### PR TITLE
Either matching

### PR DESCRIPTION
**Pull request by alexarice**
Matching component from #7

### CODE REVIEW

**Comment by alexarice** [comment]
I have had a thought/ change of heart about this. I feel that it does not feel correct for `either` to have a match function, and I think the position based matching (providing a list of functions to perform on match) is very odd. 

I propose the use of a general match function instead which functions as a C style switch statement. This could be something like
```
switch x {
  type-a = value-a;
  type-b = value-b;
  any = value;
};
```
where we first check if `x` is of type-a and return value-a if it is and so on. You could also have a function that takes `x` in place of a value if this is nicer.

**Comment by tazjin** [comment]
Interesting idea, and I think I agree! The positional matching is odd and I'm probably not going to accept it.

However one thing I'm curious about is how you scope the type names as keys to the actual types, especially with user-defined types (like `struct` and `enum`)?

**Comment by alexarice** [comment]
Good point. I guess you would need something like:
```
switch x [
  { type = type-a; action = action-a; }
  etc
]
```
Edit: Could also have a helper function that builds these:
` case = a: b: { type = a; action = b;}` 

Then you could write:
```
switch x [
  (case type-a action-a)
  (case type-b action-b)
etc
]
```

**Comment by tazjin** [comment]
At which point it might go in the direction of "too much structure to be trivially generic, too little structure to be generally useful".

If users maintained their own "type set" (similar to yants itself when you import it) it might be feasible to have a `callPackage`-style attribute in it that has a switch function for that package set. On the other hand I'm not sure I want to add yet another "Here's a strange, recursive fixed point calculation of some set"-thing ... :/

**Comment by alexarice** [comment]
Fair enough, this is easy enough to implement for the user so I'll close this for now

**Pull request closed without merging**
